apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#   app.xgeeks.org/team: idp_geekathon
#   backstage.io/kubernetes-id: stack-overflowers

namespace: idpkathon-dev
# namespace: stack-overflowers-idp_geekathon-dev

resources:
- ../../base
- ingress.yaml

  # ATENTION name = image.name NOT name = spec.containers[0].name
images:
- name: ghcr.io/xgeeks-geekathon/stack-overflowers
  newTag: cb75b48
- name: ghcr.io/xgeeks-geekathon/stack-overflowers-datafeeder
  newTag: 0bde739
